# Auto-provisions Prometheus as Grafana's default data source.
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://smartbar-prometheus:9090
    isDefault: true
    editable: true
